add_newline = false

[line_break]
disabled = true

[nodejs]
format = "via [ $version](bold green) "

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = true
